### ISSUE TITLE
Using ConEmu Output is duplicated

### ISSUE THREAD

**Issue by belotn** [JustABearOz/PSColorizer#3]
Hello,

I tried with ConEmu, the out is always dusplicated the normal one followed by the colored one

![2020-12-19 11_02_21-C__ _PoshColor_1 0 2 0](https://user-images.githubusercontent.com/3379936/102686803-44f52000-41ea-11eb-8971-421ad79d2aea.png)

Regards,
Nicolas

**Comment by JustABearOz** [comment]
Hi @belotn, this should now be working correctly in 1.0.3.0. You can grab the latest version from releases or install it directory from Powershell Gallary.

**Comment by belotn** [comment]
+1 thanks alot :)
